apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -v1
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: proxy-cm
  literals:
    - VERSION="v1"
commonLabels:
  app: proxy
  version: v1
resources:
  - deployment.yaml
